# Generated by Django 2.2.3 on 2019-07-24 00:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playGame', '0002_players_game_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='PlayerMoves',
            new_name='PlayerMove',
        ),
    ]
