# Generated by Django 2.2.3 on 2019-07-24 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playGame', '0003_auto_20190724_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_start_time', models.DateTimeField(auto_now_add=True)),
                ('game_last_active', models.DateTimeField(auto_now=True)),
                ('game_status', models.CharField(choices=[('F', 'First Player move'), ('S', 'Second Player move'), ('W', 'First Player wins'), ('w', 'Second Player wins'), ('D', 'Draw')], default='F', max_length=1)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player', to=settings.AUTH_USER_MODEL)),
                ('second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
