# Generated by Django 2.2.3 on 2019-07-25 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playGame', '0004_auto_20190724_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermove',
            name='by_first_player',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermove',
            name='game',
            field=models.ForeignKey(default=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='playGame.Game'),
            preserve_default=False,
        ),
    ]
