# Generated by Django 2.2.3 on 2019-07-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playGame', '0005_auto_20190725_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerMove',
            new_name='Move',
        ),
    ]
