# Generated by Django 2.2.3 on 2019-07-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playGame', '0007_auto_20190725_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('by_first_player', models.BooleanField(editable=False)),
                ('game', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='playGame.Game')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerMove',
        ),
    ]
